application: 
  name: 'node-lc-assembox-storage-service'
  port: 3100
  serverPath: 'assembox-storage'
  profiles.active: 'dev,local'

profiles.local:
  logger:
    level: 'verbose'
  
  docs: 
    name: 'Assembox 存储层服务'
    describe: '提供模块、组件、配置管理功能的存储层服务'
    version: 1.0
  
  # TiDB 数据库配置
  mysql:
    pfLc:
      name: 'default'
      type: 'mysql'
      host: 'dev-tidb.yearrow.com'
      port: 4000
      username: 'dev_yl_dml_deploy'
      password: 'Ckg9ytXciM'
      database: 'dev_pf_lc'
      synchronize: false
      timeout: 10000
      logging: false
  
  # Redis 缓存配置
  redis:
    host: 'redis-svc-dev.infra.svc.cluster.local'
    port: 6379
    db: 15
    username: 'dev_yl_rw_deploy'
    password: '4AEeHq39qk'
  
  # OSS 文件存储配置
  fileStorage:
    provider: 'minio'
    accessKey: 'kIE5EybIZYwJ3xTHynf6'
    secretKey: '1xDBCWi0Ob6KYWeaDnrNKBK48jdUoaEF7oCsyuE5'
    bucket: 'yunque-dev'
    secure: false
    endPoint: 192.168.5.72
    port: 30394
